#!/usr/bin/env python3
"""tools/report.py - turn a saved backtest into a markdown report with charts.

Run:
    python tools/report.py baseline                 # -> reports/backtests/baseline/report.md
    python tools/report.py baseline --benchmark SPY # add buy-and-hold comparison
    python tools/report.py baseline --png           # also write equity.png (needs matplotlib)

This is the *basic* reporter: it dumps what the engine saved. In Week 4 you build
`engine/tearsheet.py`, which adds out-of-sample sections, benchmark statistics and
walk-forward summaries - the reporter you actually ship verdicts with.
"""

from __future__ import annotations

import argparse
import json
import os
import sys

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from kit import metrics as m  # noqa: E402
from kit import spine as spine_mod  # noqa: E402


def monthly_table(equity: pd.Series) -> pd.DataFrame:
    monthly = equity.resample("ME").last()
    returns = monthly.pct_change().dropna()
    table = pd.DataFrame({"year": returns.index.year, "month": returns.index.month, "ret": returns.values})
    wide = table.pivot(index="year", columns="month", values="ret")
    wide.columns = [pd.Timestamp(2000, int(c), 1).strftime("%b") for c in wide.columns]
    wide["Year"] = monthly.pct_change().groupby(monthly.index.year).apply(lambda s: (1 + s).prod() - 1).values
    return wide


def worst_drawdowns(equity: pd.Series, top: int = 5) -> pd.DataFrame:
    dd = m.drawdown_series(equity)
    rows = []
    in_dd = False
    start = None
    for ts, value in dd.items():
        if value < 0 and not in_dd:
            in_dd, start = True, ts
        elif value == 0 and in_dd:
            window = dd.loc[start:ts]
            rows.append({"start": start.date(), "trough": window.idxmin().date(), "end": ts.date(), "depth": window.min(), "bars": len(window)})
            in_dd = False
    if in_dd:
        window = dd.loc[start:]
        rows.append({"start": start.date(), "trough": window.idxmin().date(), "end": "ongoing", "depth": window.min(), "bars": len(window)})
    frame = pd.DataFrame(rows).sort_values("depth").head(top) if rows else pd.DataFrame()
    return frame


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("name", help="saved backtest name under reports/backtests/")
    parser.add_argument("--results-dir", default=os.environ.get("PYTRADES_RESULTS", "reports/backtests"))
    parser.add_argument("--benchmark", default=None, help="symbol to compare against, e.g. SPY")
    parser.add_argument("--png", action="store_true", help="write equity.png (needs matplotlib)")
    parser.add_argument("--title", default=None)
    args = parser.parse_args()

    result = spine_mod.BacktestResult.load(args.name, args.results_dir)
    stats = result.metrics
    lines = ["# Tearsheet: %s" % (args.title or result.name), ""]
    meta = result.meta or {}
    lines += [
        "> Generated by `tools/report.py`. Engine: `%s`. Execution: `%s`. Costs: %s bps fee + %s bps slippage."
        % (meta.get("engine", "unknown"), meta.get("execution", "unknown"), meta.get("fee_bps", 0), meta.get("slippage_bps", 0)),
        "",
        "**Provenance**  ",
        "spec fingerprint `%s` · data fingerprint `%s` · %s bars, %s -> %s"
        % (
            meta.get("spec_fingerprint", "?"),
            meta.get("data_fingerprint", "?"),
            meta.get("bars", len(result.equity)),
            meta.get("first_bar", "?"),
            meta.get("last_bar", "?"),
        ),
        "",
    ]

    lines.append(m.tearsheet(stats, title="Headline metrics"))

    if args.benchmark:
        try:
            benchmark = spine_mod.load_prices(args.benchmark)
            bench = benchmark["close"].reindex(result.equity.index).ffill().dropna()
            bench_equity = bench / bench.iloc[0] * result.equity.iloc[0]
            bench_stats = m.summary(bench_equity)
            lines.append("## Benchmark: %s (buy & hold)" % args.benchmark)
            lines.append("")
            lines.append("| metric | strategy | %s | delta |" % args.benchmark)
            lines.append("| --- | --- | --- | --- |")
            for key in ("total_return", "cagr", "ann_vol", "sharpe", "sortino", "max_drawdown", "calmar"):
                lines.append(
                    "| `%s` | %s | %s | %s |"
                    % (key, m.format_metric(key, stats.get(key, float("nan"))), m.format_metric(key, bench_stats.get(key, float("nan"))), m.format_metric(key, stats.get(key, 0) - bench_stats.get(key, 0)))
                )
            lines.append("")
        except Exception as exc:  # noqa: BLE001
            lines.append("_benchmark %s unavailable: %s_" % (args.benchmark, exc))
            lines.append("")

    lines.append("## Monthly returns")
    lines.append("")
    monthly = monthly_table(result.equity)
    header = "| Year | " + " | ".join(monthly.columns) + " |"
    lines.append(header)
    lines.append("| --- |" + " --- |" * len(monthly.columns))
    for year, row in monthly.iterrows():
        cells = ["%+.1f%%" % (100 * v) if pd.notna(v) else "-" for v in row.values]
        lines.append("| %d | %s |" % (year, " | ".join(cells)))
    lines.append("")

    dd_table = worst_drawdowns(result.equity)
    lines.append("## Worst drawdowns")
    lines.append("")
    if len(dd_table):
        lines.append(_markdown_table(dd_table, floatfmt=".2%"))
    else:
        lines.append("_no drawdowns recorded_")
    lines.append("")

    if len(result.trades):
        lines.append("## Trade statistics")
        lines.append("")
        lines.append(_trade_block(stats))
        lines.append("")
        lines.append("| | |")
        lines.append("| --- | --- |")
        lines.append("| trades | %d |" % len(result.trades))
        lines.append("| first trade | %s |" % result.trades["entry_time"].min())
        lines.append("| last trade | %s |" % result.trades["exit_time"].max())
        lines.append("")

    lines.append("## Files")
    lines.append("")
    directory = os.path.join(args.results_dir, args.name)
    for filename in ("equity.csv", "positions.csv", "trades.csv", "metrics.json", "meta.json"):
        path = os.path.join(directory, filename)
        if os.path.exists(path):
            lines.append("- `%s`" % path)
    lines.append("")

    out_path = os.path.join(directory, "report.md")
    os.makedirs(directory, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print("wrote %s" % out_path)

    if args.png:
        try:
            import matplotlib

            matplotlib.use("Agg")
            import matplotlib.pyplot as plt

            fig, axes = plt.subplots(2, 1, figsize=(11, 7), sharex=True, height_ratios=[2, 1])
            axes[0].plot(result.equity.index, result.equity.values, lw=1.4)
            axes[0].set_title("Equity: %s" % result.name)
            axes[0].grid(alpha=0.3)
            axes[1].fill_between(result.equity.index, m.drawdown_series(result.equity).values, 0, alpha=0.5, color="firebrick")
            axes[1].set_title("Drawdown")
            axes[1].grid(alpha=0.3)
            fig.tight_layout()
            png_path = os.path.join(directory, "equity.png")
            fig.savefig(png_path, dpi=120)
            print("wrote %s" % png_path)
        except ImportError:
            print("matplotlib not installed - skipping chart (pip install matplotlib)")
    return 0


def _trade_block(stats: dict) -> str:
    keys = ["n_trades", "total_pnl", "win_rate", "expectancy", "profit_factor", "payoff_ratio", "breakeven_win_rate", "max_win_streak", "max_loss_streak"]
    lines = ["| Metric | Value |", "| --- | --- |"]
    for key in keys:
        if key in stats:
            lines.append("| `%s` | %s |" % (key, m.format_metric(key, stats[key])))
    return "\n".join(lines)


def _markdown_table(frame, floatfmt: str = ".2f") -> str:
    """Render a small DataFrame as a markdown table without requiring `tabulate`.

    pandas' DataFrame.to_markdown() needs the optional `tabulate` package; a
    student repo should never fail to produce a report because of an optional
    import, so fall back to a ten-line renderer.
    """
    try:
        return frame.to_markdown(index=False, floatfmt=floatfmt)
    except (ImportError, AttributeError):
        pass
    columns = [str(c) for c in frame.columns]
    lines = ["| " + " | ".join(columns) + " |", "| " + " | ".join(["---"] * len(columns)) + " |"]
    for _, row in frame.iterrows():
        cells = []
        for value in row.tolist():
            if isinstance(value, float):
                try:
                    cells.append(format(value, floatfmt))
                except (ValueError, TypeError):
                    cells.append(str(value))
            else:
                cells.append(str(value))
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)

if __name__ == "__main__":

    raise SystemExit(main())
